name: study_drill
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.10.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  google_fonts: ^8.0.1
  awesome_snackbar_content: ^0.1.8
  page_transition: ^2.2.1
  top_snackbar_flutter: ^3.3.0
  flutter_animate: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
